# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 3.0.x
    performMultiLevelLookup: true

#- task: DotNetCoreCLI@2
  # inputs:
  #  command: restore
  #  projects: '**/*.csproj'
  #  feedsToUse: config
  #  nugetConfigPath: NuGet.config    

#- task: DotNetCoreCLI@2
 # displayName: Build
 # inputs:
 #   command: build
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Visual Studio Enterprise – MPN(ce98597e-c0dc-4e5e-af71-3b86bfd5b9db)'
    azureContainerRegistry: '{"loginServer":"charan12282019.azurecr.io", "id" : "/subscriptions/ce98597e-c0dc-4e5e-af71-3b86bfd5b9db/resourceGroups/charanspieshopresources/providers/Microsoft.ContainerRegistry/registries/charan12282019"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
 #   projects: '**/*.csproj'
 #   arguments: '--configuration Release'

#steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'



